package com.kings.ttp.pojo;

public class AccountTransLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_LOG_ID
     *
     * @mbggenerated
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_TRANS_NUM
     *
     * @mbggenerated
     */
    private String transNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_ACCOUNT_ID
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_OPT_TYPE
     *
     * @mbggenerated
     */
    private Integer optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_TRANS_SRC
     *
     * @mbggenerated
     */
    private String transSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_TRANS_SRC_BILL
     *
     * @mbggenerated
     */
    private String transSrcBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    private Integer clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    private String clientImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_TRANS_DES
     *
     * @mbggenerated
     */
    private String transDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_TRANS_DES_BILL
     *
     * @mbggenerated
     */
    private String transDesBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_RMB_MONEY
     *
     * @mbggenerated
     */
    private Double rmbMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_OTHER_AMOUNT
     *
     * @mbggenerated
     */
    private Double otherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_OTHER_MONEY
     *
     * @mbggenerated
     */
    private Double otherMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_RESULT_CODE
     *
     * @mbggenerated
     */
    private Integer resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_TRANS_TIME
     *
     * @mbggenerated
     */
    private String transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account_trans_log.F_BUILD_TIME
     *
     * @mbggenerated
     */
    private String buildTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_LOG_ID
     *
     * @return the value of t_account_trans_log.F_LOG_ID
     *
     * @mbggenerated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_LOG_ID
     *
     * @param logId the value for t_account_trans_log.F_LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_TRANS_NUM
     *
     * @return the value of t_account_trans_log.F_TRANS_NUM
     *
     * @mbggenerated
     */
    public String getTransNum() {
        return transNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_TRANS_NUM
     *
     * @param transNum the value for t_account_trans_log.F_TRANS_NUM
     *
     * @mbggenerated
     */
    public void setTransNum(String transNum) {
        this.transNum = transNum == null ? null : transNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_ACCOUNT_ID
     *
     * @return the value of t_account_trans_log.F_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_ACCOUNT_ID
     *
     * @param accountId the value for t_account_trans_log.F_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_OPT_TYPE
     *
     * @return the value of t_account_trans_log.F_OPT_TYPE
     *
     * @mbggenerated
     */
    public Integer getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_OPT_TYPE
     *
     * @param optType the value for t_account_trans_log.F_OPT_TYPE
     *
     * @mbggenerated
     */
    public void setOptType(Integer optType) {
        this.optType = optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_TRANS_SRC
     *
     * @return the value of t_account_trans_log.F_TRANS_SRC
     *
     * @mbggenerated
     */
    public String getTransSrc() {
        return transSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_TRANS_SRC
     *
     * @param transSrc the value for t_account_trans_log.F_TRANS_SRC
     *
     * @mbggenerated
     */
    public void setTransSrc(String transSrc) {
        this.transSrc = transSrc == null ? null : transSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_TRANS_SRC_BILL
     *
     * @return the value of t_account_trans_log.F_TRANS_SRC_BILL
     *
     * @mbggenerated
     */
    public String getTransSrcBill() {
        return transSrcBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_TRANS_SRC_BILL
     *
     * @param transSrcBill the value for t_account_trans_log.F_TRANS_SRC_BILL
     *
     * @mbggenerated
     */
    public void setTransSrcBill(String transSrcBill) {
        this.transSrcBill = transSrcBill == null ? null : transSrcBill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_CLIENT_TYPE
     *
     * @return the value of t_account_trans_log.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_CLIENT_TYPE
     *
     * @param clientType the value for t_account_trans_log.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_CLIENT_IMEI
     *
     * @return the value of t_account_trans_log.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public String getClientImei() {
        return clientImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_CLIENT_IMEI
     *
     * @param clientImei the value for t_account_trans_log.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public void setClientImei(String clientImei) {
        this.clientImei = clientImei == null ? null : clientImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_TRANS_DES
     *
     * @return the value of t_account_trans_log.F_TRANS_DES
     *
     * @mbggenerated
     */
    public String getTransDes() {
        return transDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_TRANS_DES
     *
     * @param transDes the value for t_account_trans_log.F_TRANS_DES
     *
     * @mbggenerated
     */
    public void setTransDes(String transDes) {
        this.transDes = transDes == null ? null : transDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_TRANS_DES_BILL
     *
     * @return the value of t_account_trans_log.F_TRANS_DES_BILL
     *
     * @mbggenerated
     */
    public String getTransDesBill() {
        return transDesBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_TRANS_DES_BILL
     *
     * @param transDesBill the value for t_account_trans_log.F_TRANS_DES_BILL
     *
     * @mbggenerated
     */
    public void setTransDesBill(String transDesBill) {
        this.transDesBill = transDesBill == null ? null : transDesBill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_RMB_MONEY
     *
     * @return the value of t_account_trans_log.F_RMB_MONEY
     *
     * @mbggenerated
     */
    public Double getRmbMoney() {
        return rmbMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_RMB_MONEY
     *
     * @param rmbMoney the value for t_account_trans_log.F_RMB_MONEY
     *
     * @mbggenerated
     */
    public void setRmbMoney(Double rmbMoney) {
        this.rmbMoney = rmbMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_OTHER_AMOUNT
     *
     * @return the value of t_account_trans_log.F_OTHER_AMOUNT
     *
     * @mbggenerated
     */
    public Double getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_OTHER_AMOUNT
     *
     * @param otherAmount the value for t_account_trans_log.F_OTHER_AMOUNT
     *
     * @mbggenerated
     */
    public void setOtherAmount(Double otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_OTHER_MONEY
     *
     * @return the value of t_account_trans_log.F_OTHER_MONEY
     *
     * @mbggenerated
     */
    public Double getOtherMoney() {
        return otherMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_OTHER_MONEY
     *
     * @param otherMoney the value for t_account_trans_log.F_OTHER_MONEY
     *
     * @mbggenerated
     */
    public void setOtherMoney(Double otherMoney) {
        this.otherMoney = otherMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_RESULT_CODE
     *
     * @return the value of t_account_trans_log.F_RESULT_CODE
     *
     * @mbggenerated
     */
    public Integer getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_RESULT_CODE
     *
     * @param resultCode the value for t_account_trans_log.F_RESULT_CODE
     *
     * @mbggenerated
     */
    public void setResultCode(Integer resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_TRANS_TIME
     *
     * @return the value of t_account_trans_log.F_TRANS_TIME
     *
     * @mbggenerated
     */
    public String getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_TRANS_TIME
     *
     * @param transTime the value for t_account_trans_log.F_TRANS_TIME
     *
     * @mbggenerated
     */
    public void setTransTime(String transTime) {
        this.transTime = transTime == null ? null : transTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account_trans_log.F_BUILD_TIME
     *
     * @return the value of t_account_trans_log.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public String getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account_trans_log.F_BUILD_TIME
     *
     * @param buildTime the value for t_account_trans_log.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public void setBuildTime(String buildTime) {
        this.buildTime = buildTime == null ? null : buildTime.trim();
    }
}