package com.kings.ttp.pojo;

public class DelivPlaceBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_PLACE_ID
     *
     * @mbggenerated
     */
    private String placeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    private String provinceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_REGION_NUM
     *
     * @mbggenerated
     */
    private String regionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    private String countryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deliv_place.F_IS_DEFAULT
     *
     * @mbggenerated
     */
    private Integer isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_PLACE_ID
     *
     * @return the value of t_deliv_place.F_PLACE_ID
     *
     * @mbggenerated
     */
    public String getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_PLACE_ID
     *
     * @param placeId the value for t_deliv_place.F_PLACE_ID
     *
     * @mbggenerated
     */
    public void setPlaceId(String placeId) {
        this.placeId = placeId == null ? null : placeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_USER_ID
     *
     * @return the value of t_deliv_place.F_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_USER_ID
     *
     * @param userId the value for t_deliv_place.F_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_PROVINCE_NUM
     *
     * @return the value of t_deliv_place.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public String getProvinceNum() {
        return provinceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_PROVINCE_NUM
     *
     * @param provinceNum the value for t_deliv_place.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public void setProvinceNum(String provinceNum) {
        this.provinceNum = provinceNum == null ? null : provinceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_REGION_NUM
     *
     * @return the value of t_deliv_place.F_REGION_NUM
     *
     * @mbggenerated
     */
    public String getRegionNum() {
        return regionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_REGION_NUM
     *
     * @param regionNum the value for t_deliv_place.F_REGION_NUM
     *
     * @mbggenerated
     */
    public void setRegionNum(String regionNum) {
        this.regionNum = regionNum == null ? null : regionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_COUNTRY_NUM
     *
     * @return the value of t_deliv_place.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public String getCountryNum() {
        return countryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_COUNTRY_NUM
     *
     * @param countryNum the value for t_deliv_place.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public void setCountryNum(String countryNum) {
        this.countryNum = countryNum == null ? null : countryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_DETAIL_ADDRESS
     *
     * @return the value of t_deliv_place.F_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_DETAIL_ADDRESS
     *
     * @param detailAddress the value for t_deliv_place.F_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deliv_place.F_IS_DEFAULT
     *
     * @return the value of t_deliv_place.F_IS_DEFAULT
     *
     * @mbggenerated
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deliv_place.F_IS_DEFAULT
     *
     * @param isDefault the value for t_deliv_place.F_IS_DEFAULT
     *
     * @mbggenerated
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }
}