package com.kings.ttp.pojo;

public class GoodsBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_GOODS_ID
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_GOODS_TYPE
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_GOODS_MODE
     *
     * @mbggenerated
     */
    private Integer goodsMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_GOODS_WEIGHT
     *
     * @mbggenerated
     */
    private Double goodsWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_GOODS_SIZE
     *
     * @mbggenerated
     */
    private String goodsSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_PIC1
     *
     * @mbggenerated
     */
    private String pic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_PIC2
     *
     * @mbggenerated
     */
    private String pic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_PIC3
     *
     * @mbggenerated
     */
    private String pic3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_PIC4
     *
     * @mbggenerated
     */
    private String pic4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_PIC5
     *
     * @mbggenerated
     */
    private String pic5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_goods.F_MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_GOODS_ID
     *
     * @return the value of t_da_goods.F_GOODS_ID
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_GOODS_ID
     *
     * @param goodsId the value for t_da_goods.F_GOODS_ID
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_GOODS_TYPE
     *
     * @return the value of t_da_goods.F_GOODS_TYPE
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_GOODS_TYPE
     *
     * @param goodsType the value for t_da_goods.F_GOODS_TYPE
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_USER_ID
     *
     * @return the value of t_da_goods.F_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_USER_ID
     *
     * @param userId the value for t_da_goods.F_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_GOODS_MODE
     *
     * @return the value of t_da_goods.F_GOODS_MODE
     *
     * @mbggenerated
     */
    public Integer getGoodsMode() {
        return goodsMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_GOODS_MODE
     *
     * @param goodsMode the value for t_da_goods.F_GOODS_MODE
     *
     * @mbggenerated
     */
    public void setGoodsMode(Integer goodsMode) {
        this.goodsMode = goodsMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_GOODS_WEIGHT
     *
     * @return the value of t_da_goods.F_GOODS_WEIGHT
     *
     * @mbggenerated
     */
    public Double getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_GOODS_WEIGHT
     *
     * @param goodsWeight the value for t_da_goods.F_GOODS_WEIGHT
     *
     * @mbggenerated
     */
    public void setGoodsWeight(Double goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_GOODS_SIZE
     *
     * @return the value of t_da_goods.F_GOODS_SIZE
     *
     * @mbggenerated
     */
    public String getGoodsSize() {
        return goodsSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_GOODS_SIZE
     *
     * @param goodsSize the value for t_da_goods.F_GOODS_SIZE
     *
     * @mbggenerated
     */
    public void setGoodsSize(String goodsSize) {
        this.goodsSize = goodsSize == null ? null : goodsSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_PIC1
     *
     * @return the value of t_da_goods.F_PIC1
     *
     * @mbggenerated
     */
    public String getPic1() {
        return pic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_PIC1
     *
     * @param pic1 the value for t_da_goods.F_PIC1
     *
     * @mbggenerated
     */
    public void setPic1(String pic1) {
        this.pic1 = pic1 == null ? null : pic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_PIC2
     *
     * @return the value of t_da_goods.F_PIC2
     *
     * @mbggenerated
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_PIC2
     *
     * @param pic2 the value for t_da_goods.F_PIC2
     *
     * @mbggenerated
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_PIC3
     *
     * @return the value of t_da_goods.F_PIC3
     *
     * @mbggenerated
     */
    public String getPic3() {
        return pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_PIC3
     *
     * @param pic3 the value for t_da_goods.F_PIC3
     *
     * @mbggenerated
     */
    public void setPic3(String pic3) {
        this.pic3 = pic3 == null ? null : pic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_PIC4
     *
     * @return the value of t_da_goods.F_PIC4
     *
     * @mbggenerated
     */
    public String getPic4() {
        return pic4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_PIC4
     *
     * @param pic4 the value for t_da_goods.F_PIC4
     *
     * @mbggenerated
     */
    public void setPic4(String pic4) {
        this.pic4 = pic4 == null ? null : pic4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_PIC5
     *
     * @return the value of t_da_goods.F_PIC5
     *
     * @mbggenerated
     */
    public String getPic5() {
        return pic5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_PIC5
     *
     * @param pic5 the value for t_da_goods.F_PIC5
     *
     * @mbggenerated
     */
    public void setPic5(String pic5) {
        this.pic5 = pic5 == null ? null : pic5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_goods.F_MEMO
     *
     * @return the value of t_da_goods.F_MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_goods.F_MEMO
     *
     * @param memo the value for t_da_goods.F_MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}