package com.kings.ttp.pojo;

public class GoodsTypeBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.F_TYPE_NUM
     *
     * @mbggenerated
     */
    private String typeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.F_TYPE_NAME
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_type.F_TYPE_MEMO
     *
     * @mbggenerated
     */
    private String typeMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.F_TYPE_NUM
     *
     * @return the value of t_goods_type.F_TYPE_NUM
     *
     * @mbggenerated
     */
    public String getTypeNum() {
        return typeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.F_TYPE_NUM
     *
     * @param typeNum the value for t_goods_type.F_TYPE_NUM
     *
     * @mbggenerated
     */
    public void setTypeNum(String typeNum) {
        this.typeNum = typeNum == null ? null : typeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.F_TYPE_NAME
     *
     * @return the value of t_goods_type.F_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.F_TYPE_NAME
     *
     * @param typeName the value for t_goods_type.F_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_type.F_TYPE_MEMO
     *
     * @return the value of t_goods_type.F_TYPE_MEMO
     *
     * @mbggenerated
     */
    public String getTypeMemo() {
        return typeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_type.F_TYPE_MEMO
     *
     * @param typeMemo the value for t_goods_type.F_TYPE_MEMO
     *
     * @mbggenerated
     */
    public void setTypeMemo(String typeMemo) {
        this.typeMemo = typeMemo == null ? null : typeMemo.trim();
    }
}