package com.kings.ttp.pojo;

public class GoodsEvaluateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_EVALUATE_NUM
     *
     * @mbggenerated
     */
    private String evaluateNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_ORDER_NUM
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_SUB_NUM
     *
     * @mbggenerated
     */
    private String subNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_RECEIVE_TYPE
     *
     * @mbggenerated
     */
    private Integer receiveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_RECEIVE_USER
     *
     * @mbggenerated
     */
    private String receiveUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_SERVICE_VAL
     *
     * @mbggenerated
     */
    private Integer serviceVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_DETAIL
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_OP_TIME
     *
     * @mbggenerated
     */
    private String opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_CNT_USEFUL
     *
     * @mbggenerated
     */
    private Integer cntUseful;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_evaluate.F_CNT_UNUSEFUL
     *
     * @mbggenerated
     */
    private Integer cntUnuseful;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_EVALUATE_NUM
     *
     * @return the value of t_goods_evaluate.F_EVALUATE_NUM
     *
     * @mbggenerated
     */
    public String getEvaluateNum() {
        return evaluateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_EVALUATE_NUM
     *
     * @param evaluateNum the value for t_goods_evaluate.F_EVALUATE_NUM
     *
     * @mbggenerated
     */
    public void setEvaluateNum(String evaluateNum) {
        this.evaluateNum = evaluateNum == null ? null : evaluateNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_USER_ID
     *
     * @return the value of t_goods_evaluate.F_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_USER_ID
     *
     * @param userId the value for t_goods_evaluate.F_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_ORDER_NUM
     *
     * @return the value of t_goods_evaluate.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_ORDER_NUM
     *
     * @param orderNum the value for t_goods_evaluate.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_SUB_NUM
     *
     * @return the value of t_goods_evaluate.F_SUB_NUM
     *
     * @mbggenerated
     */
    public String getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_SUB_NUM
     *
     * @param subNum the value for t_goods_evaluate.F_SUB_NUM
     *
     * @mbggenerated
     */
    public void setSubNum(String subNum) {
        this.subNum = subNum == null ? null : subNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_RECEIVE_TYPE
     *
     * @return the value of t_goods_evaluate.F_RECEIVE_TYPE
     *
     * @mbggenerated
     */
    public Integer getReceiveType() {
        return receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_RECEIVE_TYPE
     *
     * @param receiveType the value for t_goods_evaluate.F_RECEIVE_TYPE
     *
     * @mbggenerated
     */
    public void setReceiveType(Integer receiveType) {
        this.receiveType = receiveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_RECEIVE_USER
     *
     * @return the value of t_goods_evaluate.F_RECEIVE_USER
     *
     * @mbggenerated
     */
    public String getReceiveUser() {
        return receiveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_RECEIVE_USER
     *
     * @param receiveUser the value for t_goods_evaluate.F_RECEIVE_USER
     *
     * @mbggenerated
     */
    public void setReceiveUser(String receiveUser) {
        this.receiveUser = receiveUser == null ? null : receiveUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_SERVICE_VAL
     *
     * @return the value of t_goods_evaluate.F_SERVICE_VAL
     *
     * @mbggenerated
     */
    public Integer getServiceVal() {
        return serviceVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_SERVICE_VAL
     *
     * @param serviceVal the value for t_goods_evaluate.F_SERVICE_VAL
     *
     * @mbggenerated
     */
    public void setServiceVal(Integer serviceVal) {
        this.serviceVal = serviceVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_DETAIL
     *
     * @return the value of t_goods_evaluate.F_DETAIL
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_DETAIL
     *
     * @param detail the value for t_goods_evaluate.F_DETAIL
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_OP_TIME
     *
     * @return the value of t_goods_evaluate.F_OP_TIME
     *
     * @mbggenerated
     */
    public String getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_OP_TIME
     *
     * @param opTime the value for t_goods_evaluate.F_OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(String opTime) {
        this.opTime = opTime == null ? null : opTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_CNT_USEFUL
     *
     * @return the value of t_goods_evaluate.F_CNT_USEFUL
     *
     * @mbggenerated
     */
    public Integer getCntUseful() {
        return cntUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_CNT_USEFUL
     *
     * @param cntUseful the value for t_goods_evaluate.F_CNT_USEFUL
     *
     * @mbggenerated
     */
    public void setCntUseful(Integer cntUseful) {
        this.cntUseful = cntUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_evaluate.F_CNT_UNUSEFUL
     *
     * @return the value of t_goods_evaluate.F_CNT_UNUSEFUL
     *
     * @mbggenerated
     */
    public Integer getCntUnuseful() {
        return cntUnuseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_evaluate.F_CNT_UNUSEFUL
     *
     * @param cntUnuseful the value for t_goods_evaluate.F_CNT_UNUSEFUL
     *
     * @mbggenerated
     */
    public void setCntUnuseful(Integer cntUnuseful) {
        this.cntUnuseful = cntUnuseful;
    }
}