package com.kings.ttp.pojo;

public class GpsRecInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_REC_ID
     *
     * @mbggenerated
     */
    private String recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_ORDER_NUM
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_SUB_NUM
     *
     * @mbggenerated
     */
    private String subNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_DRIVER_ID
     *
     * @mbggenerated
     */
    private String driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_DRIVER_NAME
     *
     * @mbggenerated
     */
    private String driverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    private Integer clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    private String clientImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    private String provinceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_REGION_NUM
     *
     * @mbggenerated
     */
    private String regionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    private String countryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_GPS_LONGITUDE
     *
     * @mbggenerated
     */
    private String gpsLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_GPS_LATITUDE
     *
     * @mbggenerated
     */
    private String gpsLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gps_rec.F_REC_TIME
     *
     * @mbggenerated
     */
    private String recTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_REC_ID
     *
     * @return the value of t_gps_rec.F_REC_ID
     *
     * @mbggenerated
     */
    public String getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_REC_ID
     *
     * @param recId the value for t_gps_rec.F_REC_ID
     *
     * @mbggenerated
     */
    public void setRecId(String recId) {
        this.recId = recId == null ? null : recId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_ORDER_NUM
     *
     * @return the value of t_gps_rec.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_ORDER_NUM
     *
     * @param orderNum the value for t_gps_rec.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_SUB_NUM
     *
     * @return the value of t_gps_rec.F_SUB_NUM
     *
     * @mbggenerated
     */
    public String getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_SUB_NUM
     *
     * @param subNum the value for t_gps_rec.F_SUB_NUM
     *
     * @mbggenerated
     */
    public void setSubNum(String subNum) {
        this.subNum = subNum == null ? null : subNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_DRIVER_ID
     *
     * @return the value of t_gps_rec.F_DRIVER_ID
     *
     * @mbggenerated
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_DRIVER_ID
     *
     * @param driverId the value for t_gps_rec.F_DRIVER_ID
     *
     * @mbggenerated
     */
    public void setDriverId(String driverId) {
        this.driverId = driverId == null ? null : driverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_DRIVER_NAME
     *
     * @return the value of t_gps_rec.F_DRIVER_NAME
     *
     * @mbggenerated
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_DRIVER_NAME
     *
     * @param driverName the value for t_gps_rec.F_DRIVER_NAME
     *
     * @mbggenerated
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName == null ? null : driverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_CLIENT_TYPE
     *
     * @return the value of t_gps_rec.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_CLIENT_TYPE
     *
     * @param clientType the value for t_gps_rec.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_CLIENT_IMEI
     *
     * @return the value of t_gps_rec.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public String getClientImei() {
        return clientImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_CLIENT_IMEI
     *
     * @param clientImei the value for t_gps_rec.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public void setClientImei(String clientImei) {
        this.clientImei = clientImei == null ? null : clientImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_PROVINCE_NUM
     *
     * @return the value of t_gps_rec.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public String getProvinceNum() {
        return provinceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_PROVINCE_NUM
     *
     * @param provinceNum the value for t_gps_rec.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public void setProvinceNum(String provinceNum) {
        this.provinceNum = provinceNum == null ? null : provinceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_REGION_NUM
     *
     * @return the value of t_gps_rec.F_REGION_NUM
     *
     * @mbggenerated
     */
    public String getRegionNum() {
        return regionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_REGION_NUM
     *
     * @param regionNum the value for t_gps_rec.F_REGION_NUM
     *
     * @mbggenerated
     */
    public void setRegionNum(String regionNum) {
        this.regionNum = regionNum == null ? null : regionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_COUNTRY_NUM
     *
     * @return the value of t_gps_rec.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public String getCountryNum() {
        return countryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_COUNTRY_NUM
     *
     * @param countryNum the value for t_gps_rec.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public void setCountryNum(String countryNum) {
        this.countryNum = countryNum == null ? null : countryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_GPS_LONGITUDE
     *
     * @return the value of t_gps_rec.F_GPS_LONGITUDE
     *
     * @mbggenerated
     */
    public String getGpsLongitude() {
        return gpsLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_GPS_LONGITUDE
     *
     * @param gpsLongitude the value for t_gps_rec.F_GPS_LONGITUDE
     *
     * @mbggenerated
     */
    public void setGpsLongitude(String gpsLongitude) {
        this.gpsLongitude = gpsLongitude == null ? null : gpsLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_GPS_LATITUDE
     *
     * @return the value of t_gps_rec.F_GPS_LATITUDE
     *
     * @mbggenerated
     */
    public String getGpsLatitude() {
        return gpsLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_GPS_LATITUDE
     *
     * @param gpsLatitude the value for t_gps_rec.F_GPS_LATITUDE
     *
     * @mbggenerated
     */
    public void setGpsLatitude(String gpsLatitude) {
        this.gpsLatitude = gpsLatitude == null ? null : gpsLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gps_rec.F_REC_TIME
     *
     * @return the value of t_gps_rec.F_REC_TIME
     *
     * @mbggenerated
     */
    public String getRecTime() {
        return recTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gps_rec.F_REC_TIME
     *
     * @param recTime the value for t_gps_rec.F_REC_TIME
     *
     * @mbggenerated
     */
    public void setRecTime(String recTime) {
        this.recTime = recTime == null ? null : recTime.trim();
    }
}