package com.kings.ttp.pojo;

public class OrderSubInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_SUB_NUM
     *
     * @mbggenerated
     */
    private String subNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_ORDER_NUM
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_EXT_SUB_NUM
     *
     * @mbggenerated
     */
    private String extSubNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_GOODS_NUM
     *
     * @mbggenerated
     */
    private String goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_GOODS_COUNT
     *
     * @mbggenerated
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_GOODS_PRICE
     *
     * @mbggenerated
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_VALID_DATE
     *
     * @mbggenerated
     */
    private String validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_PAY_TIME
     *
     * @mbggenerated
     */
    private String payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_CHECK_DATE
     *
     * @mbggenerated
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_ORDER_MONEY
     *
     * @mbggenerated
     */
    private Double orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_ORDER_ISPAY
     *
     * @mbggenerated
     */
    private Integer orderIspay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_ORDER_PAYMONEY
     *
     * @mbggenerated
     */
    private Double orderPaymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_ORDER_DISCOUNT
     *
     * @mbggenerated
     */
    private Double orderDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_sub.F_GOODS_MEMO
     *
     * @mbggenerated
     */
    private String goodsMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_SUB_NUM
     *
     * @return the value of t_order_sub.F_SUB_NUM
     *
     * @mbggenerated
     */
    public String getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_SUB_NUM
     *
     * @param subNum the value for t_order_sub.F_SUB_NUM
     *
     * @mbggenerated
     */
    public void setSubNum(String subNum) {
        this.subNum = subNum == null ? null : subNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_ORDER_NUM
     *
     * @return the value of t_order_sub.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_ORDER_NUM
     *
     * @param orderNum the value for t_order_sub.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_EXT_SUB_NUM
     *
     * @return the value of t_order_sub.F_EXT_SUB_NUM
     *
     * @mbggenerated
     */
    public String getExtSubNum() {
        return extSubNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_EXT_SUB_NUM
     *
     * @param extSubNum the value for t_order_sub.F_EXT_SUB_NUM
     *
     * @mbggenerated
     */
    public void setExtSubNum(String extSubNum) {
        this.extSubNum = extSubNum == null ? null : extSubNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_GOODS_NUM
     *
     * @return the value of t_order_sub.F_GOODS_NUM
     *
     * @mbggenerated
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_GOODS_NUM
     *
     * @param goodsNum the value for t_order_sub.F_GOODS_NUM
     *
     * @mbggenerated
     */
    public void setGoodsNum(String goodsNum) {
        this.goodsNum = goodsNum == null ? null : goodsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_GOODS_COUNT
     *
     * @return the value of t_order_sub.F_GOODS_COUNT
     *
     * @mbggenerated
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_GOODS_COUNT
     *
     * @param goodsCount the value for t_order_sub.F_GOODS_COUNT
     *
     * @mbggenerated
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_GOODS_PRICE
     *
     * @return the value of t_order_sub.F_GOODS_PRICE
     *
     * @mbggenerated
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_GOODS_PRICE
     *
     * @param goodsPrice the value for t_order_sub.F_GOODS_PRICE
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_VALID_DATE
     *
     * @return the value of t_order_sub.F_VALID_DATE
     *
     * @mbggenerated
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_VALID_DATE
     *
     * @param validDate the value for t_order_sub.F_VALID_DATE
     *
     * @mbggenerated
     */
    public void setValidDate(String validDate) {
        this.validDate = validDate == null ? null : validDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_PAY_TIME
     *
     * @return the value of t_order_sub.F_PAY_TIME
     *
     * @mbggenerated
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_PAY_TIME
     *
     * @param payTime the value for t_order_sub.F_PAY_TIME
     *
     * @mbggenerated
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime == null ? null : payTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_CHECK_DATE
     *
     * @return the value of t_order_sub.F_CHECK_DATE
     *
     * @mbggenerated
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_CHECK_DATE
     *
     * @param checkDate the value for t_order_sub.F_CHECK_DATE
     *
     * @mbggenerated
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate == null ? null : checkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_ORDER_MONEY
     *
     * @return the value of t_order_sub.F_ORDER_MONEY
     *
     * @mbggenerated
     */
    public Double getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_ORDER_MONEY
     *
     * @param orderMoney the value for t_order_sub.F_ORDER_MONEY
     *
     * @mbggenerated
     */
    public void setOrderMoney(Double orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_ORDER_ISPAY
     *
     * @return the value of t_order_sub.F_ORDER_ISPAY
     *
     * @mbggenerated
     */
    public Integer getOrderIspay() {
        return orderIspay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_ORDER_ISPAY
     *
     * @param orderIspay the value for t_order_sub.F_ORDER_ISPAY
     *
     * @mbggenerated
     */
    public void setOrderIspay(Integer orderIspay) {
        this.orderIspay = orderIspay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_ORDER_PAYMONEY
     *
     * @return the value of t_order_sub.F_ORDER_PAYMONEY
     *
     * @mbggenerated
     */
    public Double getOrderPaymoney() {
        return orderPaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_ORDER_PAYMONEY
     *
     * @param orderPaymoney the value for t_order_sub.F_ORDER_PAYMONEY
     *
     * @mbggenerated
     */
    public void setOrderPaymoney(Double orderPaymoney) {
        this.orderPaymoney = orderPaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_ORDER_DISCOUNT
     *
     * @return the value of t_order_sub.F_ORDER_DISCOUNT
     *
     * @mbggenerated
     */
    public Double getOrderDiscount() {
        return orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_ORDER_DISCOUNT
     *
     * @param orderDiscount the value for t_order_sub.F_ORDER_DISCOUNT
     *
     * @mbggenerated
     */
    public void setOrderDiscount(Double orderDiscount) {
        this.orderDiscount = orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_sub.F_GOODS_MEMO
     *
     * @return the value of t_order_sub.F_GOODS_MEMO
     *
     * @mbggenerated
     */
    public String getGoodsMemo() {
        return goodsMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_sub.F_GOODS_MEMO
     *
     * @param goodsMemo the value for t_order_sub.F_GOODS_MEMO
     *
     * @mbggenerated
     */
    public void setGoodsMemo(String goodsMemo) {
        this.goodsMemo = goodsMemo == null ? null : goodsMemo.trim();
    }
}