package com.kings.ttp.pojo;

public class OrderStatusBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_status.F_STATUS_NUM
     *
     * @mbggenerated
     */
    private String statusNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_status.F_STATUS_NAME
     *
     * @mbggenerated
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_status.F_STATUS_CAPTION
     *
     * @mbggenerated
     */
    private String statusCaption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_status.F_STATUS_MEMO
     *
     * @mbggenerated
     */
    private String statusMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_status.F_STATUS_NUM
     *
     * @return the value of t_order_status.F_STATUS_NUM
     *
     * @mbggenerated
     */
    public String getStatusNum() {
        return statusNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_status.F_STATUS_NUM
     *
     * @param statusNum the value for t_order_status.F_STATUS_NUM
     *
     * @mbggenerated
     */
    public void setStatusNum(String statusNum) {
        this.statusNum = statusNum == null ? null : statusNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_status.F_STATUS_NAME
     *
     * @return the value of t_order_status.F_STATUS_NAME
     *
     * @mbggenerated
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_status.F_STATUS_NAME
     *
     * @param statusName the value for t_order_status.F_STATUS_NAME
     *
     * @mbggenerated
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_status.F_STATUS_CAPTION
     *
     * @return the value of t_order_status.F_STATUS_CAPTION
     *
     * @mbggenerated
     */
    public String getStatusCaption() {
        return statusCaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_status.F_STATUS_CAPTION
     *
     * @param statusCaption the value for t_order_status.F_STATUS_CAPTION
     *
     * @mbggenerated
     */
    public void setStatusCaption(String statusCaption) {
        this.statusCaption = statusCaption == null ? null : statusCaption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_status.F_STATUS_MEMO
     *
     * @return the value of t_order_status.F_STATUS_MEMO
     *
     * @mbggenerated
     */
    public String getStatusMemo() {
        return statusMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_status.F_STATUS_MEMO
     *
     * @param statusMemo the value for t_order_status.F_STATUS_MEMO
     *
     * @mbggenerated
     */
    public void setStatusMemo(String statusMemo) {
        this.statusMemo = statusMemo == null ? null : statusMemo.trim();
    }
}