package com.kings.ttp.pojo;

public class OrderMainInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_NUM
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_INIT_NUM
     *
     * @mbggenerated
     */
    private String initNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_EXT_NUM
     *
     * @mbggenerated
     */
    private String extNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_MANCODE
     *
     * @mbggenerated
     */
    private String orderMancode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_MANNAME
     *
     * @mbggenerated
     */
    private String orderManname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_TIME
     *
     * @mbggenerated
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_MOBILE
     *
     * @mbggenerated
     */
    private String orderMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    private Integer clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    private String clientImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DELIV_PLACE_ID
     *
     * @mbggenerated
     */
    private String delivPlaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DELIV_PROVINCE_NUM
     *
     * @mbggenerated
     */
    private String delivProvinceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DELIV_REGION_NUM
     *
     * @mbggenerated
     */
    private String delivRegionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DELIV_COUNTRY_NUM
     *
     * @mbggenerated
     */
    private String delivCountryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DELIV_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    private String delivDetailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_RECEIVE_PLACE_ID
     *
     * @mbggenerated
     */
    private String receivePlaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_RECEIVE_PROVINCE_NUM
     *
     * @mbggenerated
     */
    private String receiveProvinceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_RECEIVE_REGION_NUM
     *
     * @mbggenerated
     */
    private String receiveRegionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_RECEIVE_COUNTRY_NUM
     *
     * @mbggenerated
     */
    private String receiveCountryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_RECEIVE_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    private String receiveDetailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DRIVER_ID
     *
     * @mbggenerated
     */
    private String driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DRIVER_NAME
     *
     * @mbggenerated
     */
    private String driverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DRIVER_MOBILE
     *
     * @mbggenerated
     */
    private String driverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DRIVER_CLIENT_TYPE
     *
     * @mbggenerated
     */
    private Integer driverClientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_DRIVER_CLIENT_IMEI
     *
     * @mbggenerated
     */
    private String driverClientImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_STATUS_CAPTION
     *
     * @mbggenerated
     */
    private String statusCaption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_VALID_DATE
     *
     * @mbggenerated
     */
    private String validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_PAY_TIME
     *
     * @mbggenerated
     */
    private String payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_CHECK_DATE
     *
     * @mbggenerated
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_MEMO
     *
     * @mbggenerated
     */
    private String orderMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_MONEY
     *
     * @mbggenerated
     */
    private Double orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_ISPAY
     *
     * @mbggenerated
     */
    private Integer orderIspay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_PAYMONEY
     *
     * @mbggenerated
     */
    private Double orderPaymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_ORDER_DISCOUNT
     *
     * @mbggenerated
     */
    private Double orderDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_IS_EVAL
     *
     * @mbggenerated
     */
    private Integer isEval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_LAST_MANCODE
     *
     * @mbggenerated
     */
    private String lastMancode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_LAST_MANNAME
     *
     * @mbggenerated
     */
    private String lastManname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_LAST_TIME
     *
     * @mbggenerated
     */
    private String lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_main.F_LAST_MEMO
     *
     * @mbggenerated
     */
    private String lastMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_NUM
     *
     * @return the value of t_order_main.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_NUM
     *
     * @param orderNum the value for t_order_main.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_INIT_NUM
     *
     * @return the value of t_order_main.F_INIT_NUM
     *
     * @mbggenerated
     */
    public String getInitNum() {
        return initNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_INIT_NUM
     *
     * @param initNum the value for t_order_main.F_INIT_NUM
     *
     * @mbggenerated
     */
    public void setInitNum(String initNum) {
        this.initNum = initNum == null ? null : initNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_EXT_NUM
     *
     * @return the value of t_order_main.F_EXT_NUM
     *
     * @mbggenerated
     */
    public String getExtNum() {
        return extNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_EXT_NUM
     *
     * @param extNum the value for t_order_main.F_EXT_NUM
     *
     * @mbggenerated
     */
    public void setExtNum(String extNum) {
        this.extNum = extNum == null ? null : extNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_MANCODE
     *
     * @return the value of t_order_main.F_ORDER_MANCODE
     *
     * @mbggenerated
     */
    public String getOrderMancode() {
        return orderMancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_MANCODE
     *
     * @param orderMancode the value for t_order_main.F_ORDER_MANCODE
     *
     * @mbggenerated
     */
    public void setOrderMancode(String orderMancode) {
        this.orderMancode = orderMancode == null ? null : orderMancode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_MANNAME
     *
     * @return the value of t_order_main.F_ORDER_MANNAME
     *
     * @mbggenerated
     */
    public String getOrderManname() {
        return orderManname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_MANNAME
     *
     * @param orderManname the value for t_order_main.F_ORDER_MANNAME
     *
     * @mbggenerated
     */
    public void setOrderManname(String orderManname) {
        this.orderManname = orderManname == null ? null : orderManname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_TIME
     *
     * @return the value of t_order_main.F_ORDER_TIME
     *
     * @mbggenerated
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_TIME
     *
     * @param orderTime the value for t_order_main.F_ORDER_TIME
     *
     * @mbggenerated
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_MOBILE
     *
     * @return the value of t_order_main.F_ORDER_MOBILE
     *
     * @mbggenerated
     */
    public String getOrderMobile() {
        return orderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_MOBILE
     *
     * @param orderMobile the value for t_order_main.F_ORDER_MOBILE
     *
     * @mbggenerated
     */
    public void setOrderMobile(String orderMobile) {
        this.orderMobile = orderMobile == null ? null : orderMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_CLIENT_TYPE
     *
     * @return the value of t_order_main.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_CLIENT_TYPE
     *
     * @param clientType the value for t_order_main.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_CLIENT_IMEI
     *
     * @return the value of t_order_main.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public String getClientImei() {
        return clientImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_CLIENT_IMEI
     *
     * @param clientImei the value for t_order_main.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public void setClientImei(String clientImei) {
        this.clientImei = clientImei == null ? null : clientImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DELIV_PLACE_ID
     *
     * @return the value of t_order_main.F_DELIV_PLACE_ID
     *
     * @mbggenerated
     */
    public String getDelivPlaceId() {
        return delivPlaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DELIV_PLACE_ID
     *
     * @param delivPlaceId the value for t_order_main.F_DELIV_PLACE_ID
     *
     * @mbggenerated
     */
    public void setDelivPlaceId(String delivPlaceId) {
        this.delivPlaceId = delivPlaceId == null ? null : delivPlaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DELIV_PROVINCE_NUM
     *
     * @return the value of t_order_main.F_DELIV_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public String getDelivProvinceNum() {
        return delivProvinceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DELIV_PROVINCE_NUM
     *
     * @param delivProvinceNum the value for t_order_main.F_DELIV_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public void setDelivProvinceNum(String delivProvinceNum) {
        this.delivProvinceNum = delivProvinceNum == null ? null : delivProvinceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DELIV_REGION_NUM
     *
     * @return the value of t_order_main.F_DELIV_REGION_NUM
     *
     * @mbggenerated
     */
    public String getDelivRegionNum() {
        return delivRegionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DELIV_REGION_NUM
     *
     * @param delivRegionNum the value for t_order_main.F_DELIV_REGION_NUM
     *
     * @mbggenerated
     */
    public void setDelivRegionNum(String delivRegionNum) {
        this.delivRegionNum = delivRegionNum == null ? null : delivRegionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DELIV_COUNTRY_NUM
     *
     * @return the value of t_order_main.F_DELIV_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public String getDelivCountryNum() {
        return delivCountryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DELIV_COUNTRY_NUM
     *
     * @param delivCountryNum the value for t_order_main.F_DELIV_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public void setDelivCountryNum(String delivCountryNum) {
        this.delivCountryNum = delivCountryNum == null ? null : delivCountryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DELIV_DETAIL_ADDRESS
     *
     * @return the value of t_order_main.F_DELIV_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    public String getDelivDetailAddress() {
        return delivDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DELIV_DETAIL_ADDRESS
     *
     * @param delivDetailAddress the value for t_order_main.F_DELIV_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    public void setDelivDetailAddress(String delivDetailAddress) {
        this.delivDetailAddress = delivDetailAddress == null ? null : delivDetailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_RECEIVE_PLACE_ID
     *
     * @return the value of t_order_main.F_RECEIVE_PLACE_ID
     *
     * @mbggenerated
     */
    public String getReceivePlaceId() {
        return receivePlaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_RECEIVE_PLACE_ID
     *
     * @param receivePlaceId the value for t_order_main.F_RECEIVE_PLACE_ID
     *
     * @mbggenerated
     */
    public void setReceivePlaceId(String receivePlaceId) {
        this.receivePlaceId = receivePlaceId == null ? null : receivePlaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_RECEIVE_PROVINCE_NUM
     *
     * @return the value of t_order_main.F_RECEIVE_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public String getReceiveProvinceNum() {
        return receiveProvinceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_RECEIVE_PROVINCE_NUM
     *
     * @param receiveProvinceNum the value for t_order_main.F_RECEIVE_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public void setReceiveProvinceNum(String receiveProvinceNum) {
        this.receiveProvinceNum = receiveProvinceNum == null ? null : receiveProvinceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_RECEIVE_REGION_NUM
     *
     * @return the value of t_order_main.F_RECEIVE_REGION_NUM
     *
     * @mbggenerated
     */
    public String getReceiveRegionNum() {
        return receiveRegionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_RECEIVE_REGION_NUM
     *
     * @param receiveRegionNum the value for t_order_main.F_RECEIVE_REGION_NUM
     *
     * @mbggenerated
     */
    public void setReceiveRegionNum(String receiveRegionNum) {
        this.receiveRegionNum = receiveRegionNum == null ? null : receiveRegionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_RECEIVE_COUNTRY_NUM
     *
     * @return the value of t_order_main.F_RECEIVE_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public String getReceiveCountryNum() {
        return receiveCountryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_RECEIVE_COUNTRY_NUM
     *
     * @param receiveCountryNum the value for t_order_main.F_RECEIVE_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public void setReceiveCountryNum(String receiveCountryNum) {
        this.receiveCountryNum = receiveCountryNum == null ? null : receiveCountryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_RECEIVE_DETAIL_ADDRESS
     *
     * @return the value of t_order_main.F_RECEIVE_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    public String getReceiveDetailAddress() {
        return receiveDetailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_RECEIVE_DETAIL_ADDRESS
     *
     * @param receiveDetailAddress the value for t_order_main.F_RECEIVE_DETAIL_ADDRESS
     *
     * @mbggenerated
     */
    public void setReceiveDetailAddress(String receiveDetailAddress) {
        this.receiveDetailAddress = receiveDetailAddress == null ? null : receiveDetailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DRIVER_ID
     *
     * @return the value of t_order_main.F_DRIVER_ID
     *
     * @mbggenerated
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DRIVER_ID
     *
     * @param driverId the value for t_order_main.F_DRIVER_ID
     *
     * @mbggenerated
     */
    public void setDriverId(String driverId) {
        this.driverId = driverId == null ? null : driverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DRIVER_NAME
     *
     * @return the value of t_order_main.F_DRIVER_NAME
     *
     * @mbggenerated
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DRIVER_NAME
     *
     * @param driverName the value for t_order_main.F_DRIVER_NAME
     *
     * @mbggenerated
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName == null ? null : driverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DRIVER_MOBILE
     *
     * @return the value of t_order_main.F_DRIVER_MOBILE
     *
     * @mbggenerated
     */
    public String getDriverMobile() {
        return driverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DRIVER_MOBILE
     *
     * @param driverMobile the value for t_order_main.F_DRIVER_MOBILE
     *
     * @mbggenerated
     */
    public void setDriverMobile(String driverMobile) {
        this.driverMobile = driverMobile == null ? null : driverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DRIVER_CLIENT_TYPE
     *
     * @return the value of t_order_main.F_DRIVER_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public Integer getDriverClientType() {
        return driverClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DRIVER_CLIENT_TYPE
     *
     * @param driverClientType the value for t_order_main.F_DRIVER_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public void setDriverClientType(Integer driverClientType) {
        this.driverClientType = driverClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_DRIVER_CLIENT_IMEI
     *
     * @return the value of t_order_main.F_DRIVER_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public String getDriverClientImei() {
        return driverClientImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_DRIVER_CLIENT_IMEI
     *
     * @param driverClientImei the value for t_order_main.F_DRIVER_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public void setDriverClientImei(String driverClientImei) {
        this.driverClientImei = driverClientImei == null ? null : driverClientImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_STATUS
     *
     * @return the value of t_order_main.F_ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_STATUS
     *
     * @param orderStatus the value for t_order_main.F_ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_STATUS_CAPTION
     *
     * @return the value of t_order_main.F_STATUS_CAPTION
     *
     * @mbggenerated
     */
    public String getStatusCaption() {
        return statusCaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_STATUS_CAPTION
     *
     * @param statusCaption the value for t_order_main.F_STATUS_CAPTION
     *
     * @mbggenerated
     */
    public void setStatusCaption(String statusCaption) {
        this.statusCaption = statusCaption == null ? null : statusCaption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_VALID_DATE
     *
     * @return the value of t_order_main.F_VALID_DATE
     *
     * @mbggenerated
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_VALID_DATE
     *
     * @param validDate the value for t_order_main.F_VALID_DATE
     *
     * @mbggenerated
     */
    public void setValidDate(String validDate) {
        this.validDate = validDate == null ? null : validDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_PAY_TIME
     *
     * @return the value of t_order_main.F_PAY_TIME
     *
     * @mbggenerated
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_PAY_TIME
     *
     * @param payTime the value for t_order_main.F_PAY_TIME
     *
     * @mbggenerated
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime == null ? null : payTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_CHECK_DATE
     *
     * @return the value of t_order_main.F_CHECK_DATE
     *
     * @mbggenerated
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_CHECK_DATE
     *
     * @param checkDate the value for t_order_main.F_CHECK_DATE
     *
     * @mbggenerated
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate == null ? null : checkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_MEMO
     *
     * @return the value of t_order_main.F_ORDER_MEMO
     *
     * @mbggenerated
     */
    public String getOrderMemo() {
        return orderMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_MEMO
     *
     * @param orderMemo the value for t_order_main.F_ORDER_MEMO
     *
     * @mbggenerated
     */
    public void setOrderMemo(String orderMemo) {
        this.orderMemo = orderMemo == null ? null : orderMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_MONEY
     *
     * @return the value of t_order_main.F_ORDER_MONEY
     *
     * @mbggenerated
     */
    public Double getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_MONEY
     *
     * @param orderMoney the value for t_order_main.F_ORDER_MONEY
     *
     * @mbggenerated
     */
    public void setOrderMoney(Double orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_ISPAY
     *
     * @return the value of t_order_main.F_ORDER_ISPAY
     *
     * @mbggenerated
     */
    public Integer getOrderIspay() {
        return orderIspay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_ISPAY
     *
     * @param orderIspay the value for t_order_main.F_ORDER_ISPAY
     *
     * @mbggenerated
     */
    public void setOrderIspay(Integer orderIspay) {
        this.orderIspay = orderIspay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_PAYMONEY
     *
     * @return the value of t_order_main.F_ORDER_PAYMONEY
     *
     * @mbggenerated
     */
    public Double getOrderPaymoney() {
        return orderPaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_PAYMONEY
     *
     * @param orderPaymoney the value for t_order_main.F_ORDER_PAYMONEY
     *
     * @mbggenerated
     */
    public void setOrderPaymoney(Double orderPaymoney) {
        this.orderPaymoney = orderPaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_ORDER_DISCOUNT
     *
     * @return the value of t_order_main.F_ORDER_DISCOUNT
     *
     * @mbggenerated
     */
    public Double getOrderDiscount() {
        return orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_ORDER_DISCOUNT
     *
     * @param orderDiscount the value for t_order_main.F_ORDER_DISCOUNT
     *
     * @mbggenerated
     */
    public void setOrderDiscount(Double orderDiscount) {
        this.orderDiscount = orderDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_IS_EVAL
     *
     * @return the value of t_order_main.F_IS_EVAL
     *
     * @mbggenerated
     */
    public Integer getIsEval() {
        return isEval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_IS_EVAL
     *
     * @param isEval the value for t_order_main.F_IS_EVAL
     *
     * @mbggenerated
     */
    public void setIsEval(Integer isEval) {
        this.isEval = isEval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_LAST_MANCODE
     *
     * @return the value of t_order_main.F_LAST_MANCODE
     *
     * @mbggenerated
     */
    public String getLastMancode() {
        return lastMancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_LAST_MANCODE
     *
     * @param lastMancode the value for t_order_main.F_LAST_MANCODE
     *
     * @mbggenerated
     */
    public void setLastMancode(String lastMancode) {
        this.lastMancode = lastMancode == null ? null : lastMancode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_LAST_MANNAME
     *
     * @return the value of t_order_main.F_LAST_MANNAME
     *
     * @mbggenerated
     */
    public String getLastManname() {
        return lastManname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_LAST_MANNAME
     *
     * @param lastManname the value for t_order_main.F_LAST_MANNAME
     *
     * @mbggenerated
     */
    public void setLastManname(String lastManname) {
        this.lastManname = lastManname == null ? null : lastManname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_LAST_TIME
     *
     * @return the value of t_order_main.F_LAST_TIME
     *
     * @mbggenerated
     */
    public String getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_LAST_TIME
     *
     * @param lastTime the value for t_order_main.F_LAST_TIME
     *
     * @mbggenerated
     */
    public void setLastTime(String lastTime) {
        this.lastTime = lastTime == null ? null : lastTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_main.F_LAST_MEMO
     *
     * @return the value of t_order_main.F_LAST_MEMO
     *
     * @mbggenerated
     */
    public String getLastMemo() {
        return lastMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_main.F_LAST_MEMO
     *
     * @param lastMemo the value for t_order_main.F_LAST_MEMO
     *
     * @mbggenerated
     */
    public void setLastMemo(String lastMemo) {
        this.lastMemo = lastMemo == null ? null : lastMemo.trim();
    }
}