package com.kings.ttp.pojo;

public class OrderLogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_LOG_ID
     *
     * @mbggenerated
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_ORDER_NUM
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_SUB_NUM
     *
     * @mbggenerated
     */
    private String subNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_OP_TYPE
     *
     * @mbggenerated
     */
    private Integer opType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_OP_NUM
     *
     * @mbggenerated
     */
    private String opNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    private Integer clientType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    private String clientImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_OP_MANCODE
     *
     * @mbggenerated
     */
    private String opMancode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_OP_MANNAME
     *
     * @mbggenerated
     */
    private String opManname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_OP_TIME
     *
     * @mbggenerated
     */
    private String opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_log.F_OP_MEMO
     *
     * @mbggenerated
     */
    private String opMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_LOG_ID
     *
     * @return the value of t_order_log.F_LOG_ID
     *
     * @mbggenerated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_LOG_ID
     *
     * @param logId the value for t_order_log.F_LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_ORDER_NUM
     *
     * @return the value of t_order_log.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_ORDER_NUM
     *
     * @param orderNum the value for t_order_log.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_SUB_NUM
     *
     * @return the value of t_order_log.F_SUB_NUM
     *
     * @mbggenerated
     */
    public String getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_SUB_NUM
     *
     * @param subNum the value for t_order_log.F_SUB_NUM
     *
     * @mbggenerated
     */
    public void setSubNum(String subNum) {
        this.subNum = subNum == null ? null : subNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_ORDER_STATUS
     *
     * @return the value of t_order_log.F_ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_ORDER_STATUS
     *
     * @param orderStatus the value for t_order_log.F_ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_OP_TYPE
     *
     * @return the value of t_order_log.F_OP_TYPE
     *
     * @mbggenerated
     */
    public Integer getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_OP_TYPE
     *
     * @param opType the value for t_order_log.F_OP_TYPE
     *
     * @mbggenerated
     */
    public void setOpType(Integer opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_OP_NUM
     *
     * @return the value of t_order_log.F_OP_NUM
     *
     * @mbggenerated
     */
    public String getOpNum() {
        return opNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_OP_NUM
     *
     * @param opNum the value for t_order_log.F_OP_NUM
     *
     * @mbggenerated
     */
    public void setOpNum(String opNum) {
        this.opNum = opNum == null ? null : opNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_CLIENT_TYPE
     *
     * @return the value of t_order_log.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public Integer getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_CLIENT_TYPE
     *
     * @param clientType the value for t_order_log.F_CLIENT_TYPE
     *
     * @mbggenerated
     */
    public void setClientType(Integer clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_CLIENT_IMEI
     *
     * @return the value of t_order_log.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public String getClientImei() {
        return clientImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_CLIENT_IMEI
     *
     * @param clientImei the value for t_order_log.F_CLIENT_IMEI
     *
     * @mbggenerated
     */
    public void setClientImei(String clientImei) {
        this.clientImei = clientImei == null ? null : clientImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_OP_MANCODE
     *
     * @return the value of t_order_log.F_OP_MANCODE
     *
     * @mbggenerated
     */
    public String getOpMancode() {
        return opMancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_OP_MANCODE
     *
     * @param opMancode the value for t_order_log.F_OP_MANCODE
     *
     * @mbggenerated
     */
    public void setOpMancode(String opMancode) {
        this.opMancode = opMancode == null ? null : opMancode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_OP_MANNAME
     *
     * @return the value of t_order_log.F_OP_MANNAME
     *
     * @mbggenerated
     */
    public String getOpManname() {
        return opManname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_OP_MANNAME
     *
     * @param opManname the value for t_order_log.F_OP_MANNAME
     *
     * @mbggenerated
     */
    public void setOpManname(String opManname) {
        this.opManname = opManname == null ? null : opManname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_OP_TIME
     *
     * @return the value of t_order_log.F_OP_TIME
     *
     * @mbggenerated
     */
    public String getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_OP_TIME
     *
     * @param opTime the value for t_order_log.F_OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(String opTime) {
        this.opTime = opTime == null ? null : opTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_log.F_OP_MEMO
     *
     * @return the value of t_order_log.F_OP_MEMO
     *
     * @mbggenerated
     */
    public String getOpMemo() {
        return opMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_log.F_OP_MEMO
     *
     * @param opMemo the value for t_order_log.F_OP_MEMO
     *
     * @mbggenerated
     */
    public void setOpMemo(String opMemo) {
        this.opMemo = opMemo == null ? null : opMemo.trim();
    }
}