package com.kings.ttp.pojo;

public class OrderRuleDz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dz_order_rule.F_ORDER_NUM
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dz_order_rule.F_SUB_NUM
     *
     * @mbggenerated
     */
    private String subNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dz_order_rule.F_RULE_NUM
     *
     * @mbggenerated
     */
    private String ruleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dz_order_rule.F_RULE_NAME
     *
     * @mbggenerated
     */
    private String ruleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dz_order_rule.F_ORDER_NUM
     *
     * @return the value of t_dz_order_rule.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dz_order_rule.F_ORDER_NUM
     *
     * @param orderNum the value for t_dz_order_rule.F_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dz_order_rule.F_SUB_NUM
     *
     * @return the value of t_dz_order_rule.F_SUB_NUM
     *
     * @mbggenerated
     */
    public String getSubNum() {
        return subNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dz_order_rule.F_SUB_NUM
     *
     * @param subNum the value for t_dz_order_rule.F_SUB_NUM
     *
     * @mbggenerated
     */
    public void setSubNum(String subNum) {
        this.subNum = subNum == null ? null : subNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dz_order_rule.F_RULE_NUM
     *
     * @return the value of t_dz_order_rule.F_RULE_NUM
     *
     * @mbggenerated
     */
    public String getRuleNum() {
        return ruleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dz_order_rule.F_RULE_NUM
     *
     * @param ruleNum the value for t_dz_order_rule.F_RULE_NUM
     *
     * @mbggenerated
     */
    public void setRuleNum(String ruleNum) {
        this.ruleNum = ruleNum == null ? null : ruleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dz_order_rule.F_RULE_NAME
     *
     * @return the value of t_dz_order_rule.F_RULE_NAME
     *
     * @mbggenerated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dz_order_rule.F_RULE_NAME
     *
     * @param ruleName the value for t_dz_order_rule.F_RULE_NAME
     *
     * @mbggenerated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }
}