package com.kings.ttp.pojo;

public class ShipperBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_PASSWD
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_CARD_TYPE
     *
     * @mbggenerated
     */
    private Integer cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_CARD
     *
     * @mbggenerated
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_PHOTO
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_COMPANY
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    private String provinceNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_REGION_NUM
     *
     * @mbggenerated
     */
    private String regionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    private String countryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_contact_address
     *
     * @mbggenerated
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.f_email
     *
     * @mbggenerated
     */
    private String fEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_TELNUM
     *
     * @mbggenerated
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_CONTACT_USER
     *
     * @mbggenerated
     */
    private String contactUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_CONTACT_MOBILE
     *
     * @mbggenerated
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_CONTACT_TEL
     *
     * @mbggenerated
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_ATTACH_FILE
     *
     * @mbggenerated
     */
    private String attachFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_BUILD_TIME
     *
     * @mbggenerated
     */
    private String buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_shipper.F_MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_USER_ID
     *
     * @return the value of t_user_shipper.F_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_USER_ID
     *
     * @param userId the value for t_user_shipper.F_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_PASSWD
     *
     * @return the value of t_user_shipper.F_PASSWD
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_PASSWD
     *
     * @param passwd the value for t_user_shipper.F_PASSWD
     *
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_NAME
     *
     * @return the value of t_user_shipper.F_NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_NAME
     *
     * @param name the value for t_user_shipper.F_NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_CARD_TYPE
     *
     * @return the value of t_user_shipper.F_CARD_TYPE
     *
     * @mbggenerated
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_CARD_TYPE
     *
     * @param cardType the value for t_user_shipper.F_CARD_TYPE
     *
     * @mbggenerated
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_CARD
     *
     * @return the value of t_user_shipper.F_CARD
     *
     * @mbggenerated
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_CARD
     *
     * @param card the value for t_user_shipper.F_CARD
     *
     * @mbggenerated
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_MOBILE
     *
     * @return the value of t_user_shipper.F_MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_MOBILE
     *
     * @param mobile the value for t_user_shipper.F_MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_PHOTO
     *
     * @return the value of t_user_shipper.F_PHOTO
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_PHOTO
     *
     * @param photo the value for t_user_shipper.F_PHOTO
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_COMPANY
     *
     * @return the value of t_user_shipper.F_COMPANY
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_COMPANY
     *
     * @param company the value for t_user_shipper.F_COMPANY
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_STATUS
     *
     * @return the value of t_user_shipper.F_STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_STATUS
     *
     * @param status the value for t_user_shipper.F_STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_PROVINCE_NUM
     *
     * @return the value of t_user_shipper.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public String getProvinceNum() {
        return provinceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_PROVINCE_NUM
     *
     * @param provinceNum the value for t_user_shipper.F_PROVINCE_NUM
     *
     * @mbggenerated
     */
    public void setProvinceNum(String provinceNum) {
        this.provinceNum = provinceNum == null ? null : provinceNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_REGION_NUM
     *
     * @return the value of t_user_shipper.F_REGION_NUM
     *
     * @mbggenerated
     */
    public String getRegionNum() {
        return regionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_REGION_NUM
     *
     * @param regionNum the value for t_user_shipper.F_REGION_NUM
     *
     * @mbggenerated
     */
    public void setRegionNum(String regionNum) {
        this.regionNum = regionNum == null ? null : regionNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_COUNTRY_NUM
     *
     * @return the value of t_user_shipper.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public String getCountryNum() {
        return countryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_COUNTRY_NUM
     *
     * @param countryNum the value for t_user_shipper.F_COUNTRY_NUM
     *
     * @mbggenerated
     */
    public void setCountryNum(String countryNum) {
        this.countryNum = countryNum == null ? null : countryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_contact_address
     *
     * @return the value of t_user_shipper.F_contact_address
     *
     * @mbggenerated
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_contact_address
     *
     * @param contactAddress the value for t_user_shipper.F_contact_address
     *
     * @mbggenerated
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.f_email
     *
     * @return the value of t_user_shipper.f_email
     *
     * @mbggenerated
     */
    public String getfEmail() {
        return fEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.f_email
     *
     * @param fEmail the value for t_user_shipper.f_email
     *
     * @mbggenerated
     */
    public void setfEmail(String fEmail) {
        this.fEmail = fEmail == null ? null : fEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_TELNUM
     *
     * @return the value of t_user_shipper.F_TELNUM
     *
     * @mbggenerated
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_TELNUM
     *
     * @param telnum the value for t_user_shipper.F_TELNUM
     *
     * @mbggenerated
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum == null ? null : telnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_CONTACT_USER
     *
     * @return the value of t_user_shipper.F_CONTACT_USER
     *
     * @mbggenerated
     */
    public String getContactUser() {
        return contactUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_CONTACT_USER
     *
     * @param contactUser the value for t_user_shipper.F_CONTACT_USER
     *
     * @mbggenerated
     */
    public void setContactUser(String contactUser) {
        this.contactUser = contactUser == null ? null : contactUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_CONTACT_MOBILE
     *
     * @return the value of t_user_shipper.F_CONTACT_MOBILE
     *
     * @mbggenerated
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_CONTACT_MOBILE
     *
     * @param contactMobile the value for t_user_shipper.F_CONTACT_MOBILE
     *
     * @mbggenerated
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_CONTACT_TEL
     *
     * @return the value of t_user_shipper.F_CONTACT_TEL
     *
     * @mbggenerated
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_CONTACT_TEL
     *
     * @param contactTel the value for t_user_shipper.F_CONTACT_TEL
     *
     * @mbggenerated
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_ATTACH_FILE
     *
     * @return the value of t_user_shipper.F_ATTACH_FILE
     *
     * @mbggenerated
     */
    public String getAttachFile() {
        return attachFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_ATTACH_FILE
     *
     * @param attachFile the value for t_user_shipper.F_ATTACH_FILE
     *
     * @mbggenerated
     */
    public void setAttachFile(String attachFile) {
        this.attachFile = attachFile == null ? null : attachFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_BUILD_TIME
     *
     * @return the value of t_user_shipper.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public String getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_BUILD_TIME
     *
     * @param buildTime the value for t_user_shipper.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public void setBuildTime(String buildTime) {
        this.buildTime = buildTime == null ? null : buildTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_shipper.F_MEMO
     *
     * @return the value of t_user_shipper.F_MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_shipper.F_MEMO
     *
     * @param memo the value for t_user_shipper.F_MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}