package com.kings.ttp.pojo;

public class TradeRuleTypeBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule_type.F_RULE_TYPE_NUM
     *
     * @mbggenerated
     */
    private String ruleTypeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule_type.F_RULE_TYPE_NAME
     *
     * @mbggenerated
     */
    private String ruleTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule_type.F_RULE_TYPE_MEMO
     *
     * @mbggenerated
     */
    private String ruleTypeMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule_type.F_RULE_TYPE_NUM
     *
     * @return the value of t_trade_rule_type.F_RULE_TYPE_NUM
     *
     * @mbggenerated
     */
    public String getRuleTypeNum() {
        return ruleTypeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule_type.F_RULE_TYPE_NUM
     *
     * @param ruleTypeNum the value for t_trade_rule_type.F_RULE_TYPE_NUM
     *
     * @mbggenerated
     */
    public void setRuleTypeNum(String ruleTypeNum) {
        this.ruleTypeNum = ruleTypeNum == null ? null : ruleTypeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule_type.F_RULE_TYPE_NAME
     *
     * @return the value of t_trade_rule_type.F_RULE_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getRuleTypeName() {
        return ruleTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule_type.F_RULE_TYPE_NAME
     *
     * @param ruleTypeName the value for t_trade_rule_type.F_RULE_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setRuleTypeName(String ruleTypeName) {
        this.ruleTypeName = ruleTypeName == null ? null : ruleTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule_type.F_RULE_TYPE_MEMO
     *
     * @return the value of t_trade_rule_type.F_RULE_TYPE_MEMO
     *
     * @mbggenerated
     */
    public String getRuleTypeMemo() {
        return ruleTypeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule_type.F_RULE_TYPE_MEMO
     *
     * @param ruleTypeMemo the value for t_trade_rule_type.F_RULE_TYPE_MEMO
     *
     * @mbggenerated
     */
    public void setRuleTypeMemo(String ruleTypeMemo) {
        this.ruleTypeMemo = ruleTypeMemo == null ? null : ruleTypeMemo.trim();
    }
}