package com.kings.ttp.pojo;

public class TradeRuleBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule.F_RULE_NUM
     *
     * @mbggenerated
     */
    private String ruleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule.F_RULE_TYPE
     *
     * @mbggenerated
     */
    private String ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule.F_RULE_NAME
     *
     * @mbggenerated
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule.F_IS_USE
     *
     * @mbggenerated
     */
    private Integer isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_rule.F_RULE_MEMO
     *
     * @mbggenerated
     */
    private String ruleMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule.F_RULE_NUM
     *
     * @return the value of t_trade_rule.F_RULE_NUM
     *
     * @mbggenerated
     */
    public String getRuleNum() {
        return ruleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule.F_RULE_NUM
     *
     * @param ruleNum the value for t_trade_rule.F_RULE_NUM
     *
     * @mbggenerated
     */
    public void setRuleNum(String ruleNum) {
        this.ruleNum = ruleNum == null ? null : ruleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule.F_RULE_TYPE
     *
     * @return the value of t_trade_rule.F_RULE_TYPE
     *
     * @mbggenerated
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule.F_RULE_TYPE
     *
     * @param ruleType the value for t_trade_rule.F_RULE_TYPE
     *
     * @mbggenerated
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule.F_RULE_NAME
     *
     * @return the value of t_trade_rule.F_RULE_NAME
     *
     * @mbggenerated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule.F_RULE_NAME
     *
     * @param ruleName the value for t_trade_rule.F_RULE_NAME
     *
     * @mbggenerated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule.F_IS_USE
     *
     * @return the value of t_trade_rule.F_IS_USE
     *
     * @mbggenerated
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule.F_IS_USE
     *
     * @param isUse the value for t_trade_rule.F_IS_USE
     *
     * @mbggenerated
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_rule.F_RULE_MEMO
     *
     * @return the value of t_trade_rule.F_RULE_MEMO
     *
     * @mbggenerated
     */
    public String getRuleMemo() {
        return ruleMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_rule.F_RULE_MEMO
     *
     * @param ruleMemo the value for t_trade_rule.F_RULE_MEMO
     *
     * @mbggenerated
     */
    public void setRuleMemo(String ruleMemo) {
        this.ruleMemo = ruleMemo == null ? null : ruleMemo.trim();
    }
}