package com.kings.ttp.pojo;

public class TrainBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_ID
     *
     * @mbggenerated
     */
    private String trainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_NUM
     *
     * @mbggenerated
     */
    private String trainNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_LENGTH
     *
     * @mbggenerated
     */
    private Double trainLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_WIDTH
     *
     * @mbggenerated
     */
    private Double trainWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_HEIGHT
     *
     * @mbggenerated
     */
    private Double trainHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_SIZE
     *
     * @mbggenerated
     */
    private Double trainSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_MAX_WEIGHT
     *
     * @mbggenerated
     */
    private Double trainMaxWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_TRAIN_BRAND
     *
     * @mbggenerated
     */
    private String trainBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_BEEN_RUNNED
     *
     * @mbggenerated
     */
    private Integer beenRunned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_FACTORY_TIME
     *
     * @mbggenerated
     */
    private String factoryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_BUILD_TIME
     *
     * @mbggenerated
     */
    private String buildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_PIC1
     *
     * @mbggenerated
     */
    private String pic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_PIC2
     *
     * @mbggenerated
     */
    private String pic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_PIC3
     *
     * @mbggenerated
     */
    private String pic3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_PIC4
     *
     * @mbggenerated
     */
    private String pic4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_PIC5
     *
     * @mbggenerated
     */
    private String pic5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_da_train.F_MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_ID
     *
     * @return the value of t_da_train.F_TRAIN_ID
     *
     * @mbggenerated
     */
    public String getTrainId() {
        return trainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_ID
     *
     * @param trainId the value for t_da_train.F_TRAIN_ID
     *
     * @mbggenerated
     */
    public void setTrainId(String trainId) {
        this.trainId = trainId == null ? null : trainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_NUM
     *
     * @return the value of t_da_train.F_TRAIN_NUM
     *
     * @mbggenerated
     */
    public String getTrainNum() {
        return trainNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_NUM
     *
     * @param trainNum the value for t_da_train.F_TRAIN_NUM
     *
     * @mbggenerated
     */
    public void setTrainNum(String trainNum) {
        this.trainNum = trainNum == null ? null : trainNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_LENGTH
     *
     * @return the value of t_da_train.F_TRAIN_LENGTH
     *
     * @mbggenerated
     */
    public Double getTrainLength() {
        return trainLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_LENGTH
     *
     * @param trainLength the value for t_da_train.F_TRAIN_LENGTH
     *
     * @mbggenerated
     */
    public void setTrainLength(Double trainLength) {
        this.trainLength = trainLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_WIDTH
     *
     * @return the value of t_da_train.F_TRAIN_WIDTH
     *
     * @mbggenerated
     */
    public Double getTrainWidth() {
        return trainWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_WIDTH
     *
     * @param trainWidth the value for t_da_train.F_TRAIN_WIDTH
     *
     * @mbggenerated
     */
    public void setTrainWidth(Double trainWidth) {
        this.trainWidth = trainWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_HEIGHT
     *
     * @return the value of t_da_train.F_TRAIN_HEIGHT
     *
     * @mbggenerated
     */
    public Double getTrainHeight() {
        return trainHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_HEIGHT
     *
     * @param trainHeight the value for t_da_train.F_TRAIN_HEIGHT
     *
     * @mbggenerated
     */
    public void setTrainHeight(Double trainHeight) {
        this.trainHeight = trainHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_SIZE
     *
     * @return the value of t_da_train.F_TRAIN_SIZE
     *
     * @mbggenerated
     */
    public Double getTrainSize() {
        return trainSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_SIZE
     *
     * @param trainSize the value for t_da_train.F_TRAIN_SIZE
     *
     * @mbggenerated
     */
    public void setTrainSize(Double trainSize) {
        this.trainSize = trainSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_MAX_WEIGHT
     *
     * @return the value of t_da_train.F_TRAIN_MAX_WEIGHT
     *
     * @mbggenerated
     */
    public Double getTrainMaxWeight() {
        return trainMaxWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_MAX_WEIGHT
     *
     * @param trainMaxWeight the value for t_da_train.F_TRAIN_MAX_WEIGHT
     *
     * @mbggenerated
     */
    public void setTrainMaxWeight(Double trainMaxWeight) {
        this.trainMaxWeight = trainMaxWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_TRAIN_BRAND
     *
     * @return the value of t_da_train.F_TRAIN_BRAND
     *
     * @mbggenerated
     */
    public String getTrainBrand() {
        return trainBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_TRAIN_BRAND
     *
     * @param trainBrand the value for t_da_train.F_TRAIN_BRAND
     *
     * @mbggenerated
     */
    public void setTrainBrand(String trainBrand) {
        this.trainBrand = trainBrand == null ? null : trainBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_BEEN_RUNNED
     *
     * @return the value of t_da_train.F_BEEN_RUNNED
     *
     * @mbggenerated
     */
    public Integer getBeenRunned() {
        return beenRunned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_BEEN_RUNNED
     *
     * @param beenRunned the value for t_da_train.F_BEEN_RUNNED
     *
     * @mbggenerated
     */
    public void setBeenRunned(Integer beenRunned) {
        this.beenRunned = beenRunned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_FACTORY_TIME
     *
     * @return the value of t_da_train.F_FACTORY_TIME
     *
     * @mbggenerated
     */
    public String getFactoryTime() {
        return factoryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_FACTORY_TIME
     *
     * @param factoryTime the value for t_da_train.F_FACTORY_TIME
     *
     * @mbggenerated
     */
    public void setFactoryTime(String factoryTime) {
        this.factoryTime = factoryTime == null ? null : factoryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_BUILD_TIME
     *
     * @return the value of t_da_train.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public String getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_BUILD_TIME
     *
     * @param buildTime the value for t_da_train.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public void setBuildTime(String buildTime) {
        this.buildTime = buildTime == null ? null : buildTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_PIC1
     *
     * @return the value of t_da_train.F_PIC1
     *
     * @mbggenerated
     */
    public String getPic1() {
        return pic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_PIC1
     *
     * @param pic1 the value for t_da_train.F_PIC1
     *
     * @mbggenerated
     */
    public void setPic1(String pic1) {
        this.pic1 = pic1 == null ? null : pic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_PIC2
     *
     * @return the value of t_da_train.F_PIC2
     *
     * @mbggenerated
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_PIC2
     *
     * @param pic2 the value for t_da_train.F_PIC2
     *
     * @mbggenerated
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_PIC3
     *
     * @return the value of t_da_train.F_PIC3
     *
     * @mbggenerated
     */
    public String getPic3() {
        return pic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_PIC3
     *
     * @param pic3 the value for t_da_train.F_PIC3
     *
     * @mbggenerated
     */
    public void setPic3(String pic3) {
        this.pic3 = pic3 == null ? null : pic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_PIC4
     *
     * @return the value of t_da_train.F_PIC4
     *
     * @mbggenerated
     */
    public String getPic4() {
        return pic4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_PIC4
     *
     * @param pic4 the value for t_da_train.F_PIC4
     *
     * @mbggenerated
     */
    public void setPic4(String pic4) {
        this.pic4 = pic4 == null ? null : pic4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_PIC5
     *
     * @return the value of t_da_train.F_PIC5
     *
     * @mbggenerated
     */
    public String getPic5() {
        return pic5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_PIC5
     *
     * @param pic5 the value for t_da_train.F_PIC5
     *
     * @mbggenerated
     */
    public void setPic5(String pic5) {
        this.pic5 = pic5 == null ? null : pic5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_da_train.F_MEMO
     *
     * @return the value of t_da_train.F_MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_da_train.F_MEMO
     *
     * @param memo the value for t_da_train.F_MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}