package com.kings.ttp.pojo;

public class TrainDirverDz  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dz_train_dirver.F_STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dz_train_dirver.F_STATUS
     *
     * @return the value of t_dz_train_dirver.F_STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dz_train_dirver.F_STATUS
     *
     * @param status the value for t_dz_train_dirver.F_STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}