package com.kings.ttp.pojo;

public class UserCreditBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.F_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.F_USER_TYPE
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.F_USER_CREDIT
     *
     * @mbggenerated
     */
    private Double userCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_credit.F_LAST_TIME
     *
     * @mbggenerated
     */
    private String lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.F_USER_ID
     *
     * @return the value of t_user_credit.F_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.F_USER_ID
     *
     * @param userId the value for t_user_credit.F_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.F_USER_TYPE
     *
     * @return the value of t_user_credit.F_USER_TYPE
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.F_USER_TYPE
     *
     * @param userType the value for t_user_credit.F_USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.F_USER_CREDIT
     *
     * @return the value of t_user_credit.F_USER_CREDIT
     *
     * @mbggenerated
     */
    public Double getUserCredit() {
        return userCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.F_USER_CREDIT
     *
     * @param userCredit the value for t_user_credit.F_USER_CREDIT
     *
     * @mbggenerated
     */
    public void setUserCredit(Double userCredit) {
        this.userCredit = userCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_credit.F_LAST_TIME
     *
     * @return the value of t_user_credit.F_LAST_TIME
     *
     * @mbggenerated
     */
    public String getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_credit.F_LAST_TIME
     *
     * @param lastTime the value for t_user_credit.F_LAST_TIME
     *
     * @mbggenerated
     */
    public void setLastTime(String lastTime) {
        this.lastTime = lastTime == null ? null : lastTime.trim();
    }
}