package com.kings.ttp.pojo;

public class UserAccountBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_ACCOUNT_ID
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_RMB_MONEY
     *
     * @mbggenerated
     */
    private Double rmbMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_OTHER_AMOUNT
     *
     * @mbggenerated
     */
    private Double otherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_OTHER_MONEY
     *
     * @mbggenerated
     */
    private Double otherMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_MIN_MONEY
     *
     * @mbggenerated
     */
    private Double minMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_MAX_MONEY
     *
     * @mbggenerated
     */
    private Double maxMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_account.F_BUILD_TIME
     *
     * @mbggenerated
     */
    private String buildTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_ACCOUNT_ID
     *
     * @return the value of t_user_account.F_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_ACCOUNT_ID
     *
     * @param accountId the value for t_user_account.F_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_USER_ID
     *
     * @return the value of t_user_account.F_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_USER_ID
     *
     * @param userId the value for t_user_account.F_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_STATUS
     *
     * @return the value of t_user_account.F_STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_STATUS
     *
     * @param status the value for t_user_account.F_STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_RMB_MONEY
     *
     * @return the value of t_user_account.F_RMB_MONEY
     *
     * @mbggenerated
     */
    public Double getRmbMoney() {
        return rmbMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_RMB_MONEY
     *
     * @param rmbMoney the value for t_user_account.F_RMB_MONEY
     *
     * @mbggenerated
     */
    public void setRmbMoney(Double rmbMoney) {
        this.rmbMoney = rmbMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_OTHER_AMOUNT
     *
     * @return the value of t_user_account.F_OTHER_AMOUNT
     *
     * @mbggenerated
     */
    public Double getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_OTHER_AMOUNT
     *
     * @param otherAmount the value for t_user_account.F_OTHER_AMOUNT
     *
     * @mbggenerated
     */
    public void setOtherAmount(Double otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_OTHER_MONEY
     *
     * @return the value of t_user_account.F_OTHER_MONEY
     *
     * @mbggenerated
     */
    public Double getOtherMoney() {
        return otherMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_OTHER_MONEY
     *
     * @param otherMoney the value for t_user_account.F_OTHER_MONEY
     *
     * @mbggenerated
     */
    public void setOtherMoney(Double otherMoney) {
        this.otherMoney = otherMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_MIN_MONEY
     *
     * @return the value of t_user_account.F_MIN_MONEY
     *
     * @mbggenerated
     */
    public Double getMinMoney() {
        return minMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_MIN_MONEY
     *
     * @param minMoney the value for t_user_account.F_MIN_MONEY
     *
     * @mbggenerated
     */
    public void setMinMoney(Double minMoney) {
        this.minMoney = minMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_MAX_MONEY
     *
     * @return the value of t_user_account.F_MAX_MONEY
     *
     * @mbggenerated
     */
    public Double getMaxMoney() {
        return maxMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_MAX_MONEY
     *
     * @param maxMoney the value for t_user_account.F_MAX_MONEY
     *
     * @mbggenerated
     */
    public void setMaxMoney(Double maxMoney) {
        this.maxMoney = maxMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_account.F_BUILD_TIME
     *
     * @return the value of t_user_account.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public String getBuildTime() {
        return buildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_account.F_BUILD_TIME
     *
     * @param buildTime the value for t_user_account.F_BUILD_TIME
     *
     * @mbggenerated
     */
    public void setBuildTime(String buildTime) {
        this.buildTime = buildTime == null ? null : buildTime.trim();
    }
}