--创建用户及授权
CREATE USER 'ttp'@'localhost' IDENTIFIED BY 'ttp123';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `ttp`.* TO 'ttp'@'localhost';

GRANT GRANT OPTION ON `ttp`.* TO 'ttp'@'localhost';

--系统参数表
CREATE TABLE `T_SYSTEM` (
`F_CSBM`  varchar(32) NOT NULL COMMENT '参数编码，主键' ,
`F_CSMC`  varchar(100) NOT NULL COMMENT '参数名称，不允许重复' ,
`F_CSZ`  varchar(1000) NULL COMMENT '参数值' ,
`F_BZ`  varchar(1000) NULL COMMENT '备注信息' ,
PRIMARY KEY (`F_CSBM`)
);

--